### ISSUE TITLE
Fail to replicate results on validation set

### ISSUE THREAD

**Issue by dangne** [aymeric-roucher/GAIA#2]
Hi Aymeric,

I am trying to replicate your results on the leaderboard. The only modification I made was switching from OpenAI to AzureOpenAI. I am using `gpt-4o-2024-05-13`, and my results on the GAIA validation set are as follows:
- Level 1: 0.4906 (vs yours: 0.5849)
- Level 2: 0.3256 (vs yours: 0.4302)
- Level 3: 0.1154 (vs yours: 0.1923)

Could you please advise if there might be something I have overlooked?

Thank you so much!

**Comment by aymeric-roucher** [comment]
Hello @dangne,
It's hard to say, but here are a few hypotheses (maybe several are true):
- you could have a failure in a specific package, that for instance causes all file loadings to fail
- maybe your web browser does not work properly
- maybe you're not using agent planning (by passing `planning_interval` as in `gaia.py`)
- maybe you've made other changes to the script that downgrade scores
